"""LLM Decision Backend

Decision backend implementation based on Large Language Models (vLLM/OpenAI API).
Generates conversation responses through HTTP calls to LLM API.
"""

import json
import logging
from typing import Any, Dict, List, Optional

import httpx
import numpy as np

from ..base import DecisionBackend
from ..prompt_builder import PromptBuilder

logger = logging.getLogger(__name__)


class LLMBackend(DecisionBackend):
    """LLM Decision Backend

    Calls LLM APIs like vLLM/OpenAI to generate conversation responses.
    Supports conditioning LLM behavior through personality vectors.
    """

    def __init__(
        self,
        llm_endpoint: str,
        model_name: str,
        temperature: float = 0.8,
        max_tokens: int = 256,
        base_system_prompt: str = "",
    ):
        """Initialize LLM backend

        Args:
            llm_endpoint: LLM API endpoint URL
            model_name: Model name
            temperature: Generation temperature
            max_tokens: Maximum generation tokens
            base_system_prompt: Base system prompt
        """
        self.endpoint = llm_endpoint
        self.model_name = model_name
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.prompt_builder = PromptBuilder(base_system_prompt)
        self._client = httpx.Client(timeout=60.0)

    def generate_response(
        self,
        user_input: str,
        personality_vector: np.ndarray,
        conversation_history: List[Dict],
        context: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Generate response using LLM"""
        # Build complete prompt
        prompt_text = self.prompt_builder.build_prompt_text(
            personality_vector, conversation_history, user_input
        )

        # Call LLM API
        try:
            response = self._call_llm_api(prompt_text)
            return response
        except Exception as e:
            logger.error("LLM API call failed: %s", e)
            return f"[System Error] Unable to generate response: {e}"

    def _call_llm_api(self, prompt: str) -> str:
        """Call LLM API

        Compatible with vLLM's /v1/gentext endpoint and /generate endpoint.

        Args:
            prompt: Complete prompt text

        Returns:
            Text generated by LLM
        """
        payload = {
            "prompt": prompt,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
        }

        response = self._client.post(
            self.endpoint,
            json=payload,
            headers={"Content-Type": "application/json"},
        )
        response.raise_for_status()

        result = response.json()

        # Compatible with different API formats
        if "text" in result:
            return result["text"].strip()
        elif "generated_text" in result:
            return result["generated_text"].strip()
        elif "choices" in result:
            return result["choices"][0]["text"].strip()
        else:
            logger.warning("Unexpected API response format: %s", result.keys())
            return str(result)

    def update_model(self, training_data: List[Dict]) -> bool:
        """LLM typically does not support online updates"""
        logger.debug("LLM backend does not support online model updates")
        return False

    def evaluate_action(
        self, action: str, state: Dict, personality_vector: np.ndarray
    ) -> float:
        """LLM backend returns maximum utility by default"""
        return 1.0

    def get_backend_info(self) -> Dict[str, Any]:
        """Return backend information"""
        return {
            "type": "llm",
            "model": self.model_name,
            "endpoint": self.endpoint,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
        }

    def close(self) -> None:
        """Close HTTP client"""
        self._client.close()

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass
