"""LLM Decision Backend

Decision backend implementation based on Large Language Models.
Supports multiple LLM providers: vLLM, Ollama, OpenAI-compatible APIs.
"""

import json
import logging
from enum import Enum
from typing import Any, Dict, List, Optional

import httpx
import numpy as np

from ..base import DecisionBackend
from ..prompt_builder import PromptBuilder

logger = logging.getLogger(__name__)


class LLMProvider(str, Enum):
    """Supported LLM provider types"""
    VLLM = "vllm"
    OLLAMA = "ollama"
    OPENAI = "openai"


class LLMBackend(DecisionBackend):
    """LLM Decision Backend

    Supports multiple LLM providers:
    - vLLM: /v1/completions (OpenAI-compatible)
    - Ollama: /api/generate
    - OpenAI: /v1/chat/completions
    """

    def __init__(
        self,
        llm_endpoint: str,
        model_name: str,
        provider: str = "vllm",
        api_key: Optional[str] = None,
        temperature: float = 0.8,
        max_tokens: int = 256,
        base_system_prompt: str = "",
    ):
        """Initialize LLM backend

        Args:
            llm_endpoint: LLM API endpoint URL
            model_name: Model name
            provider: Provider type (vllm/ollama/openai)
            api_key: API key for authentication (required for OpenAI)
            temperature: Generation temperature
            max_tokens: Maximum generation tokens
            base_system_prompt: Base system prompt
        """
        self.endpoint = llm_endpoint
        self.model_name = model_name
        self.provider = LLMProvider(provider.lower())
        self.api_key = api_key
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.prompt_builder = PromptBuilder(base_system_prompt)
        
        # Setup HTTP client with appropriate headers
        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
        
        self._client = httpx.Client(timeout=60.0, headers=headers)
        logger.info(f"Initialized LLM backend: provider={self.provider}, model={self.model_name}")

    def generate_response(
        self,
        user_input: str,
        personality_vector: np.ndarray,
        conversation_history: List[Dict],
        context: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Generate response using LLM"""
        # Build complete prompt
        prompt_text = self.prompt_builder.build_prompt_text(
            personality_vector, conversation_history, user_input
        )

        # Call LLM API
        try:
            response = self._call_llm_api(prompt_text)
            return response
        except Exception as e:
            logger.error("LLM API call failed: %s", e)
            return f"[System Error] Unable to generate response: {e}"

    def _call_llm_api(self, prompt: str) -> str:
        """Call LLM API with provider-specific format

        Args:
            prompt: Complete prompt text

        Returns:
            Text generated by LLM
        """
        if self.provider == LLMProvider.VLLM:
            return self._call_vllm(prompt)
        elif self.provider == LLMProvider.OLLAMA:
            return self._call_ollama(prompt)
        elif self.provider == LLMProvider.OPENAI:
            return self._call_openai(prompt)
        else:
            raise ValueError(f"Unsupported provider: {self.provider}")

    def _call_vllm(self, prompt: str) -> str:
        """Call vLLM API (OpenAI-compatible /v1/completions)"""
        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
        }

        response = self._client.post(self.endpoint, json=payload)
        response.raise_for_status()
        result = response.json()

        # OpenAI completions format
        if "choices" in result and len(result["choices"]) > 0:
            return result["choices"][0]["text"].strip()
        else:
            logger.warning("Unexpected vLLM response format: %s", result.keys())
            return str(result)

    def _call_ollama(self, prompt: str) -> str:
        """Call Ollama API (/api/generate)"""
        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": self.temperature,
                "num_predict": self.max_tokens,
            },
        }

        response = self._client.post(self.endpoint, json=payload)
        response.raise_for_status()
        result = response.json()

        # Ollama format
        if "response" in result:
            return result["response"].strip()
        else:
            logger.warning("Unexpected Ollama response format: %s", result.keys())
            return str(result)

    def _call_openai(self, prompt: str) -> str:
        """Call OpenAI API (/v1/chat/completions)"""
        payload = {
            "model": self.model_name,
            "messages": [
                {"role": "user", "content": prompt}
            ],
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
        }

        response = self._client.post(self.endpoint, json=payload)
        response.raise_for_status()
        result = response.json()

        # OpenAI chat format
        if "choices" in result and len(result["choices"]) > 0:
            return result["choices"][0]["message"]["content"].strip()
        else:
            logger.warning("Unexpected OpenAI response format: %s", result.keys())
            return str(result)

    def update_model(self, training_data: List[Dict]) -> bool:
        """LLM typically does not support online updates"""
        logger.debug("LLM backend does not support online model updates")
        return False

    def evaluate_action(
        self, action: str, state: Dict, personality_vector: np.ndarray
    ) -> float:
        """LLM backend returns maximum utility by default"""
        return 1.0

    def get_backend_info(self) -> Dict[str, Any]:
        """Return backend information"""
        return {
            "type": "llm",
            "provider": self.provider.value,
            "model": self.model_name,
            "endpoint": self.endpoint,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
        }

    def close(self) -> None:
        """Close HTTP client"""
        self._client.close()

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass
